# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20161022_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='AS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pathupdate',
            name='path',
        ),
        migrations.AddField(
            model_name='pathupdate',
            name='path',
            field=models.ManyToManyField(to='rest.AS'),
        ),
    ]
