# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20161022_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathupdate',
            name='path',
        ),
        migrations.AddField(
            model_name='pathupdate',
            name='paths',
            field=models.ManyToManyField(related_name='updates', to='rest.AS'),
        ),
        migrations.AlterField(
            model_name='pathupdate',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='rest.Peer'),
        ),
        migrations.AlterField(
            model_name='pathupdate',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='rest.Prefix'),
        ),
    ]
